name: I like Toast and Programming!
description: I like Toast and Programming!
meta_description: "I like Toast and Programming! A blog about software development"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-56954286-1'
disqus: true
disqus_shortname: 'iliketoastandprogramming'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Kevin'
authorTwitter:  'toastshaman'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
