baseURL = 'https://blog.toastshaman.com/'
languageCode = 'en-gb'
title = 'The Programming Bibliophile'
theme = 'paper'
publishDir = 'docs'

disqusShortname = 'toastshaman'

[params]
  GoogleAnalyticsID = 'G-0809XBT1KC'
  
  color = 'gray'

  twitter = 'toastshaman'
  github = 'toastshaman'
  instagram = 'toastshaman'

  # home page profile
  avatar = 'kevin.denver@gmail.com'
  name = 'Kevin Denver'
  bio = 'Full time creative and bibliophile.'

  # misc
  disableHLJS = true
  monoDarkIcon = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
